package launcher

import (
	"fmt"
	"regexp"
	"runtime"
	"strings"
)

func DetectLauncherType(target string) LauncherType {
	if strings.HasPrefix(target, "http://") || strings.HasPrefix(target, "https://") {
		return TypeURL
	}

	sshPattern := regexp.MustCompile(`^[a-zA-Z0-9_-]+@[\w\.\-]+$`)
	if sshPattern.MatchString(target) {
		return TypeSSH
	}

	if strings.Contains(target, " ") || strings.ContainsAny(target, "|><&;") {
		return TypeCommand
	}

	return TypeApplication
}

func GenerateScript(target string, metadata *LauncherMetadata) string {
	switch metadata.Type {
	case TypeURL:
		return generateURLScript(target)
	case TypeSSH:
		return generateSSHScript(target, metadata.SSHConfig)
	case TypeCommand:
		return generateCommandScript(target, metadata.Env)
	default:
		return generateAppScript(target, metadata.Env)
	}
}

func generateURLScript(url string) string {
	var cmd string
	switch runtime.GOOS {
	case "darwin":
		cmd = fmt.Sprintf(`open "%s"`, url)
	case "linux":
		cmd = fmt.Sprintf(`xdg-open "%s"`, url)
	default:
		cmd = fmt.Sprintf(`echo "Unsupported platform: %s"`, runtime.GOOS)
	}

	return fmt.Sprintf(`#!/bin/sh
# Generated by aka - URL launcher
%s
`, cmd)
}

func generateSSHScript(target string, config *SSHConfig) string {
	var cmd string

	if config != nil && config.Password != "" {
		port := config.Port
		if port == 0 {
			port = 22
		}

		keyFlag := ""
		if config.KeyFile != "" {
			keyFlag = fmt.Sprintf(` -i "%s"`, config.KeyFile)
		}

		portFlag := ""
		if port != 22 {
			portFlag = fmt.Sprintf(" -p %d", port)
		}

		cmd = fmt.Sprintf(`sshpass -p '%s' ssh%s%s %s`, config.Password, keyFlag, portFlag, target)
	} else {
		cmd = fmt.Sprintf(`ssh %s`, target)
	}

	return fmt.Sprintf(`#!/bin/sh
# Generated by aka - SSH launcher
%s
`, cmd)
}

func generateCommandScript(command string, env map[string]string) string {
	envVars := ""
	if len(env) > 0 {
		for key, value := range env {
			envVars += fmt.Sprintf("export %s=\"%s\"\n", key, value)
		}
	}

	return fmt.Sprintf(`#!/bin/sh
# Generated by aka - Command launcher
%s%s
`, envVars, command)
}

func generateAppScript(appName string, env map[string]string) string {
	envVars := ""
	if len(env) > 0 {
		for key, value := range env {
			envVars += fmt.Sprintf("export %s=\"%s\"\n", key, value)
		}
	}

	var cmd string
	switch runtime.GOOS {
	case "darwin":
		cmd = fmt.Sprintf(`open -a "%s" "$@"`, appName)
	case "linux":
		cmd = fmt.Sprintf(`xdg-open "$@" || echo "Error: Could not open with %s"`, appName)
	default:
		cmd = fmt.Sprintf(`echo "Unsupported platform: %s"`, runtime.GOOS)
	}

	return fmt.Sprintf(`#!/bin/sh
# Generated by aka - launcher for %s
%s%s
`, appName, envVars, cmd)
}
